account/urls.py
from django.urls import path, re_path, include
from .views import register_view,  profile_edit 

urlpatterns = [
    re_path(r'^register/', register_view, name='register'),
    path('', include('django.contrib.auth.urls')),
    path('profile/', profile_edit, name='user_profile'),
]

cake_shop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import AboutView, ContactView

urlpatterns = [
        path('admin/', admin.site.urls),
        path('catalog/', include('catalog.urls')),
        path('account/', include('account.urls')),
         path('bot/', include('telegram_bot.urls')),
        path('about/', AboutView.as_view(), name='about'),
        path('contacts/', ContactView.as_view(), name='contacts'),
        path('dreamtaste', views.home_page, name='home_page'),  
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path, re_path
from .views import category_list, product_list, product_detail, order_success, order_list_of_all_users, order_create, wish_list, wish_like, wish_dislike, order_list_user_self, user_reviews, calculate_order_cost, search

urlpatterns = [
    path('categories', category_list, name='category_list'),
    path('search/', search, name='search'),
    path('category/<slug:category_slug>/', product_list, name='product_list'),  
    path('product/<slug:product_slug>/', product_detail, name='product_detail'),
    path('order/create/', order_create, name='order_create'),
    path('order/success/', order_success, name='order_success'),
    path('order/calculate_cost/', calculate_order_cost, name='calculate_order_cost'),
    path('orders_of_users/', order_list_of_all_users, name='order_list_of_all_users'),
    path('my_orders/', order_list_user_self, name='order_list_user_self'),
    path('my-reviews/', user_reviews, name='user_reviews'),
    path('wishes/', wish_list, name='wish_list'),
    path('wishes/like/', wish_like, name='wish_like'),
    path('wishes/dislike/', wish_dislike, name='wish_dislike'),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Модель Категории продукции
class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True, default="default-slug") 

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

# Модель Продукта (изделия)
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True, default="slug") 
    ingredients = models.TextField(default="default")
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product_images/%Y/%m/%d')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Изделие'
        verbose_name_plural = 'Изделия'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('product_detail',
                        args=[self.slug])

# Модель Декора
class Decoration(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        verbose_name = 'Декор'
        verbose_name_plural = 'Декоры'

    def __str__(self):
        return f"{self.name} ({self.description}) - {self.price} бел.руб."
    
# Модель Заказа
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    delivery_method = models.CharField(max_length=50, choices=[('pickup', 'Самовывоз'), ('delivery', 'Доставка')])
    delivery_address = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Заказ #{self.id} от {self.user.username} - {self.delivery_method} ({self.created_at.strftime('%Y-%m-%d %H:%M')})"

# Модель позиции в заказе  
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    weight = models.FloatField(null=True, blank=True) 
    quantity = models.PositiveIntegerField(null=True, blank=True) 
    decoration = models.ForeignKey(Decoration, null=True, blank=True, on_delete=models.SET_NULL)
    wishes = models.TextField(blank=True)  
    product_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)  
    decoration_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)  
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)  

    def __str__(self):
        return f"{self.product.name} in {self.order}"
    
# Модель Отзыв  
class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Отзыв от {self.user.username} о {self.product.name}"

# Модель Пожеланий
class Wish(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="wishes")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField()
    likes = models.PositiveIntegerField(default=0)
    dislikes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.user.username} - {self.description[:20]}"
    
# Модель Голосов для реализации системы голосования в Разделе "Пожелания"
class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    wish = models.ForeignKey(Wish, on_delete=models.CASCADE)
    vote_type = models.CharField(max_length=10)  # 'like' или 'dislike'
    
    class Meta:
        unique_together = (('user', 'wish', 'vote_type'),)  # Уникальное сочетание пользователь-пожелание-тип голоса 
    

catalog/forms.py
from django import forms
from .models import Order, OrderItem, Decoration, Product, Wish, Review

# Форма Заказа
class OrderForm(forms.ModelForm):
    
    product = forms.ModelChoiceField(
        queryset=Product.objects.all(),
        label="Товар",
        widget=forms.Select(attrs={'id': 'product-select'}),
    )
    weight = forms.FloatField(required=False, label="Вес (кг)", min_value=1)
    quantity = forms.IntegerField(required=False, label="Количество (шт)", min_value=1)
    decoration = forms.ModelChoiceField(queryset=Decoration.objects.all(), label="Сложность декора")
    wishes = forms.CharField(
        required=False, 
        label="Пожелания по декору",
        widget=forms.Textarea(attrs={'rows': 5, 'cols': 20})
    )
    
    delivery_method = forms.ChoiceField(
        choices=[('pickup', 'Самовывоз'), ('delivery', 'Доставка')],
        label="Способ доставки"
    )
    delivery_address = forms.CharField(required=False, max_length=255, label="Адрес доставки")

    class Meta:
        model = Order
        fields = ['product', 'decoration', 'wishes', 'delivery_method', 'delivery_address']

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)

        self.fields['product'].label_from_instance = lambda obj: f"{obj.category}: {obj.name} ({obj.price} руб.)"

    def clean(self):
        cleaned_data = super().clean()
        product = cleaned_data.get("product")
        
        if product and product.category == 'Торты':
            self.fields['quantity'].widget.attrs['readonly'] = False  # Разрешаем ввод количества
            self.fields['weight'].widget.attrs.pop('readonly', None)  # Разрешаем ввод веса
        else:
            self.fields['weight'].widget.attrs['readonly'] = 'readonly'  # Блокируем поле веса
            self.fields['quantity'].widget.attrs['readonly'] = False  # Разрешаем ввод количества
        return cleaned_data

# Форма Пожелания о включении продукции
class WishForm(forms.ModelForm):
    class Meta:
        model = Wish
        fields = ['category', 'description']
        widgets = {
            'description': forms.Textarea(attrs={'placeholder': 'Опишите изделие, которое вы желаете видеть в нашем ассортименте...'}),
        }
        labels = {
            'category': 'Категория',  
            'description': 'Описание изделия',  
        }

# Форма для отправки Отзыва
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'placeholder': 'Ваш отзыв...', 'rows': 10, 'cols': 40}),
        }
        labels = {
            'text': 'Текст',  
        }

catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from decimal import Decimal, InvalidOperation
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.db.models import Q
import re

from .models import Category, Product, Order, OrderItem, Wish, Review, Vote, Decoration
from .forms import OrderForm, WishForm, ReviewForm

# Список категорий
def category_list(request):
    categories = Category.objects.all()
    return render(request, 'category_list.html', {'categories': categories})

# Список изделий определенной категории
def product_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    categories = Category.objects.all()
    products = category.products.all()
    return render(request, 
                  'product_list.html', 
                  {'category': category,
                   'categories': categories,
                   'products': products})

# Детальная информация об изделии, функционал отзывов
def product_detail(request, product_slug):
    product = get_object_or_404(Product, slug=product_slug)
    reviews = product.reviews.all()

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.product = product
            review.user = request.user
            review.save()
            return redirect('product_detail', product_slug=product.slug)
    else:
        form = ReviewForm()

    return render(request, 
                  'product_detail.html', 
                  {'product': product, 
                   'reviews': reviews,
                   'form': form})

# Создание заказа
@login_required
def order_create(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.save()

            product = form.cleaned_data['product']
            weight = form.cleaned_data['weight']
            quantity = form.cleaned_data['quantity']
            decoration = form.cleaned_data['decoration']
            product_price = product.price
            decoration_price = decoration.price if decoration else 0

            order_item = OrderItem(
                order=order,
                product=product,
                weight=weight,
                quantity=quantity,
                decoration=decoration,
                wishes=form.cleaned_data['wishes'],
                product_price=product_price,
                decoration_price=decoration_price,
                total_price = (product_price * (Decimal(weight) if weight else Decimal(quantity)) + decoration_price)
            )
            order_item.save()

            return redirect('order_success') 
    else:
        form = OrderForm()
    return render(request, 'order_form.html', {'form': form})

# Успешная отправка формы заказа
def order_success(request):
    return render(request, 'order_success.html')

# Расчет стоимости заказа
@login_required
def calculate_order_cost(request):
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        weight = request.POST.get('weight')
        if not weight or Decimal(weight) <= 0:
            return JsonResponse({'error': 'Invalid weight'}, status=400)
        quantity = request.POST.get('quantity')
        decoration_id = request.POST.get('decoration_id')
        
        product = Product.objects.get(id=product_id)
        decoration = Decoration.objects.get(id=decoration_id) if decoration_id else None

        product_price = product.price
        decoration_price = decoration.price if decoration else 0

        # print(f"Product ID: {product_id}, Category: {product.category.id}, Weight: {weight}, Quantity: {quantity}, Decoration ID: {decoration_id}")  # Отладка

        # Логика расчета стоимости
        if product.category.name == 'Торты':
            try:
                total_price = decoration_price + (product_price * Decimal(weight) * Decimal(quantity))
            except InvalidOperation:
                return JsonResponse({'error': 'Invalid weight or quantity'}, status=400)
        else:
            total_price = decoration_price + (product_price * int(quantity))

        return JsonResponse({'total_price': total_price.quantize(Decimal('0.01'))})
    return JsonResponse({'error': 'Invalid request'}, status=400)

# Список заказов всех пользователей для администратора
@staff_member_required
def order_list_of_all_users(request):
    orders = Order.objects.all()
    return render(request, 'order_list_of_all_users.html', {'orders': orders})

# Список заказов конкретного пользователя (информация в личном кабинете)
@login_required
def order_list_user_self(request):
    orders = Order.objects.filter(user=request.user).prefetch_related('orderitem_set')
    return render(request, 'order_list_user_self.html', {'orders': orders})

# Список отзывов конкретного пользователя (информация в личном кабинете)
@login_required
def user_reviews(request):
    reviews = Review.objects.filter(user=request.user)
    return render(request, 'user_reviews.html', {'reviews': reviews})

# Отправка пожелания и демонстрация всех пожеланий пользователей
def wish_list(request):
    if request.method == 'POST':
        form = WishForm(request.POST)
        if form.is_valid():
            wish = form.save(commit=False)
            wish.user = request.user
            wish.save()
            return redirect('wish_list')
    else:
        form = WishForm()

    wishes = Wish.objects.all()
    return render(request, 'wish_list.html', {'form': form, 'wishes': wishes})

# Система голосования за изделие в пожелании
# likes
@login_required
def wish_like(request):
    if request.method == 'POST':
        wish_id = request.POST.get('id')
        wish = get_object_or_404(Wish, id=wish_id)

        # Проверяем, проголосовал ли пользователь ранее
        vote, created = Vote.objects.get_or_create(user=request.user, wish=wish, defaults={'vote_type': 'like'})
        
        if not created: 
            if vote.vote_type == 'like':
                vote.delete()
                wish.likes -= 1
            else:
                vote.vote_type = 'like'
                vote.save()
                wish.likes += 1
                wish.dislikes -= 1
        else:  # Новый голос
            wish.likes += 1

        wish.save()
        return JsonResponse({'likes': wish.likes, 'dislikes': wish.dislikes})

# dislikes
@login_required
def wish_dislike(request):
    if request.method == 'POST':
        wish_id = request.POST.get('id')
        wish = get_object_or_404(Wish, id=wish_id)

        vote, created = Vote.objects.get_or_create(user=request.user, wish=wish, defaults={'vote_type': 'dislike'})
        
        if not created:  
            if vote.vote_type == 'dislike':
                vote.delete()
                wish.dislikes -= 1
            else:
                vote.vote_type = 'dislike'
                vote.save()
                wish.dislikes += 1
                wish.likes -= 1
        else:
            wish.dislikes += 1

        wish.save()
        return JsonResponse({'likes': wish.likes, 'dislikes': wish.dislikes})

# Поиск по сайту   
def search(request):
    products_results = []
    searched = ''
    if request.method == "POST":
        searched = request.POST.get('searched', '').strip()
        if searched:
            search_terms = searched.split()
            queries = Q()
            for term in search_terms:
                term_query = (
                    Q(name__icontains=term) |
                    Q(category__name__icontains=term) |
                    Q(ingredients__icontains=term) |
                    Q(description__icontains=term)
                )
                queries &= term_query
            products_results = Product.objects.filter(queries).distinct()
    context = {
        'searched': searched,
        'products_results': products_results
    }
    
    return render(request, "search/search_results.html", context=context)

catalog/templates/category_list.html
{% extends "base_generic.html" %}
    
{% block content %}
    <h1>Наша продукция</h1>
    <ul>
        {% for category in categories %}
            <li><a href="{% url 'product_list' category.slug %}">{{ category.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

catalog/templates/order_form.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Форма заказа</h1>
<form method="post">
{% csrf_token %}
    <table>
        <tr>
            <td><label for="product-select">Товар</label></td>
            <td>{{ form.product }}</td>  
        </tr>
        <tr>
          <td>{{ form.weight.label_tag }}</td>
          <td>{{ form.weight }}</td>
        </tr>
        <tr>
            <td>{{ form.quantity.label_tag }}</td>
            <td>{{ form.quantity }}</td>
        </tr>
        <tr>
            <td>{{ form.decoration.label_tag }}</td>
            <td>{{ form.decoration }}</td>
        </tr>
        <tr>
            <td>{{ form.wishes.label_tag }}</td>
            <td>{{ form.wishes }}</td>
        </tr>
        <tr>
            <td>{{ form.delivery_method.label_tag }}</td>
            <td>{{ form.delivery_method }}</td>
        </tr>
        <tr id="pickup-options" style="display: none;">
            <td>Выберите кондитерскую:</td>
            <td>
                <label><input type="radio" name="bakery" value="Кондитерская №1"> Кондитерская №1</label>
                <label><input type="radio" name="bakery" value="Кондитерская №2"> Кондитерская №2</label>
            </td>
        </tr>
        <tr id="delivery-address" style="display: none;">
            <td>{{ form.delivery_address.label_tag }}</td>
            <td>{{ form.delivery_address }}</td>
        </tr>
        <tr>
            <td>Стоимость заказа:</td>
            <td>
                <span id="total-cost">0.00</span> руб.
                <button type="button" id="calculate-cost" class="button_wish">Рассчитать стоимость</button>
            </td>
        </tr>
    </table>
    <button type="submit" class="button_wish">Отправить заказ</button>
</form>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
    function toggleDeliveryFields() {
        var deliveryMethod = $('#id_delivery_method').val();
        if (deliveryMethod === 'pickup') {
            $('#pickup-options').show();
            $('#delivery-address').hide();
        } else if (deliveryMethod === 'delivery') {
            $('#pickup-options').hide();
            $('#delivery-address').show();
        } else {
            $('#pickup-options').hide();
            $('#delivery-address').hide();
        }
    }
    // Инициализация
    toggleDeliveryFields(); 
    // Обработчик события нажатия на кнопку "Рассчитать стоимость"
    $('#calculate-cost').click(function() {
        var productId = $('#product-select').val();
        var weight = $('#id_weight').val().trim();
        if (!weight || isNaN(parseFloat(weight)) || parseFloat(weight) <= 0) {
            alert('Введите корректный вес');
            return;
        }
        var quantity = $('#id_quantity').val().trim();
        var decorationId = $('#id_decoration').val();

        $.ajax({
            url: "{% url 'calculate_order_cost' %}",
            type: "POST",
            data: {
                'product_id': productId,
                'weight': weight,
                'quantity': quantity,
                'decoration_id': decorationId,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function(data) {
                console.log(data);
                var totalPrice = parseFloat(data.total_price);
                $('#total-cost').text(totalPrice.toFixed(2));
            },
            error: function(xhr) {
                alert('Ошибка при расчете стоимости');
            }
        });
    });
    // События
    $('#product-select').change(toggleDeliveryFields);
    $('#id_delivery_method').change(function() {
        toggleDeliveryFields();
    });
});
</script>
{% endblock %}

catalog/templates/order_list.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Список заказов</h1>
<table>
    <tr>
        <th>Товар</th>
        <th>Вес/Количество</th>
        <th>Пожелания</th>
        <th>Способ доставки</th>
        <th>Адрес доставки</th>
        <th>Дата создания</th>
    </tr>
    {% for order in orders %}
    <tr>
        <td>{{ order.product.name }}</td>
        <td>{{ order.weight_or_quantity }}</td>
        <td>{{ order.wishes }}</td>
        <td>{{ order.delivery_method }}</td>
        <td>{{ order.delivery_address }}</td>
        <td>{{ order.created_at }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

catalog/templates/order_list_of_all_users.html
{% extends "base_generic.html" %}

{% block title %}Список заказов{% endblock %}

{% block content %}
<h2>Список всех заказов клиентов</h2>
<ul>
    {% for order in orders %}
        <li>
            <strong>Номер заказа:</strong> {{ order.id }}<br>
            <strong>Данные о пользователе:</strong><br>
            <strong>Имя:</strong> {{ order.user.first_name }}<br>
            <strong>Фамилия:</strong> {{ order.user.last_name }}<br>
            <strong>Почта:</strong> {{ order.user.email }}<br>
            <strong>Телефон:</strong> {{ order.user.profile.phone }}<br>
            <strong>Дата создания:</strong> {{ order.created_at }}<br>
            <strong>Метод доставки:</strong> {{ order.get_delivery_method_display }}<br>
            {% if order.delivery_method == 'delivery' %}
                <strong>Адрес доставки:</strong> {{ order.delivery_address }}<br>
            {% endif %}
            <strong>Детали заказа:</strong>
            <ul>
                {% for item in order.orderitem_set.all %}
                    <li>
                        <strong>Продукт:</strong> {{ item.product.name }}<br>
                        <strong>Вес:</strong> {{ item.weight }} кг<br>
                        <strong>Количество:</strong> {{ item.quantity }} шт.<br>
                        <strong>Пожелания по декору:</strong> {{ item.wishes }}<br>
                        <strong>Сложность декора:</strong> {{ item.decoration }}<br>
                        <strong>Стоимость заказа:</strong> {{ item.total_price }}<br>
                    </li>
                {% empty %}
                    <li>Нет деталей заказа.</li>
                {% endfor %}
            </ul>
        </li>
    {% empty %}
        <li>Нет заказов.</li>
    {% endfor %}
</ul>
{% endblock %}

catalog/templates/order_list_user_self.html
{% extends "base_generic.html" %}
{% block content %}
    <h2>Ваши заказы</h2>
    {% for order in orders %}
        <div class="card_order_list">
            <strong>Номер заказа:</strong> {{ order.id }}<br>
            <strong>Дата создания:</strong> {{ order.created_at }}<br>
            <strong>Метод доставки:</strong> {{ order.get_delivery_method_display }}<br>
            {% if order.delivery_method == 'delivery' %}
                <strong>Адрес доставки:</strong> {{ order.delivery_address }}<br>
            {% endif %}
            {% for item in order.orderitem_set.all %}
                <div class="order_item">
                    <strong>Продукт:</strong> {{ item.product.category.name }} - {{ item.product.name }}<br>
                    <strong>Вес:</strong> {{ item.weight }} кг<br>
                    <strong>Количество:</strong> {{ item.quantity }} шт.<br>
                    <strong>Пожелания по декору:</strong> {{ item.wishes }}<br>
                    <strong>Сложность декора:</strong> {{ item.decoration }}<br>
                    <strong>Стоимость заказа:</strong> {{ item.total_price }}<br>
                </div>
            {% empty %}
                <p>Нет товаров в заказе.</p>
            {% endfor %}
        </div>
    {% empty %}
        <p>Нет заказов.</p>
    {% endfor %}
{% endblock %}

catalog/templates/order_success.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>Заказ успешно отправлен!</h1>
    <p>Спасибо за ваш заказ. Мы свяжемся с вами в ближайшее время.</p>
    <a href="{% url 'order_create' %}">Сделать новый заказ</a>
{% endblock %}

catalog/templates/product_detail.html
{% extends "base_generic.html" %}
{% block content %}
    <div class="product-card">
        <div class="product-details">
            <h1>{{ product.name }}</h1>
            <p>Состав: {{ product.ingredients }}</p>
            <p>Описание: {{ product.description }}</p>
            <p>Цена: {{ product.price }} бел.руб. за 1кг/1шт</p>
        </div>
        <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-image">
    </div>
    
    <h2>Отзывы</h2>
    <div>
        {% for review in reviews %}
            <div class="review">
                <p>ID:{{ review.user.id }} | <strong>{{ review.user.first_name }}</strong></p>
                <p>{{ review.text }}</p> 
                <p><em>{{ review.created_at }}</em></p>
            </div>
        {% empty %}
            <p>Нет отзывов.</p>
        {% endfor %}
    </div>
    
    <h3>Написать отзыв</h3>
    {% if user.is_authenticated %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button_wish">Отправить отзыв</button>
    </form>
    {% else %}
    <p>Авторизируйся, чтобы оставить отзыв</p>
        <a href="{% url 'login' %}?next={{ request.path }}" class="btn btn-primary">Войти в аккаунт</a>
    {% endif %}
    
    <p><a href="{% url 'product_list' product.category.slug %}">Назад</a></p>
{% endblock %}

catalog/templates/product_list.html
{% extends "base_generic.html" %}
{% block content %}
    <h1>{{ category.name }}</h1>
    <div class="product-list">
        {% for product in products %}
            <div class="product-card-list">
                <div class="product-content-list">
                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                    <p>Состав: {{ product.ingredients }}</p>
                    <p>Описание: {{ product.description|slice:":50" }}...</p>
                    <p>Цена: {{ product.price }} руб.</p>
                </div>
                <div class="product-image-list">
                    <img src="{{ product.image.url }}" alt="{{ product.name }}">
                </div>
            </div>
        {% endfor %}
    </div>
    <a href="{% url 'category_list' %}">Назад</a>
{% endblock %}

catalog/templates/user_reviews.html
{% extends "base_generic.html" %}

{% block content %}
<h2>Ваши отзывы</h2>
<ul>
    {% for review in reviews %}
        <li>
            <strong>Отзыв на:</strong> {{ review.product.name }}<br>
            <strong>Текст отзыва:</strong> {{ review.text }}<br>
            <strong>Дата отзыва:</strong> {{ review.created_at|date:"d.m.Y" }}<br>
        </li>
    {% empty %}
        <li>Нет отзывов.</li>
    {% endfor %}
</ul>
{% endblock %}
  

catalog/templates/wish_list.html
{% extends 'base_generic.html' %}
{% block content %}
    <h1>Пожелания</h1>
    {% if user.is_authenticated %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="button_wish">Отправить пожелание</button>
        </form>
    {% else %}
        <p>Авторизируйся, чтобы оставить пожелание</p>
        <a href="{% url 'login' %}?next={{ request.path }}" class="btn btn-primary">Войти в аккаунт</a>
    {% endif %}
    <br>
    <h2> Пожелания по кондитерским изделиям:</h2>
    <div>
        <div class="wish-card">
            <table border="0">
                <tr>
                    <td>№</td>
                    <td>Категория:</td>
                    <td>Описание:</td>
                </tr>
                {% for wish in wishes %}
                <tr>
                    <td>{{ wish.id }}</td>
                    <td>{{ wish.category.name }}</td>
                    <td>{{ wish.description }}</td>
                    <td>
                        <button class="like-button button_wish" data-wish-id="{{ wish.id }}">Нравится ({{ wish.likes }})</button>
                        <button class="dislike-button button_wish" data-wish-id="{{ wish.id }}">Не нравится ({{ wish.dislikes }})</button>
                    </td>
                </tr>
                {% empty %}
                <p>Нет пожеланий.</p>
                {% endfor %}
            </table>
        </div>
    </div>
    <meta name="csrf-token" content="{{ csrf_token }}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
    $(document).ready(function() {
        var csrfToken = $('meta[name="csrf-token"]').attr('content');

        $('.like-button').click(function() {
            var wishId = $(this).data('wish-id');
            var button = $(this);
            $.ajax({
                type: 'POST',
                url: "{% url 'wish_like' %}",
                data: {
                    id: wishId,
                    csrfmiddlewaretoken: csrfToken 
                },
                success: function(data) {
                    button.text('Нравится (' + data.likes + ')');
                }
            });
        });

        $('.dislike-button').click(function() {
            var wishId = $(this).data('wish-id');
            var button = $(this);
            $.ajax({
                type: 'POST',
                url: "{% url 'wish_dislike' %}",
                data: {
                    id: wishId,
                    csrfmiddlewaretoken: csrfToken  
                },
                success: function(data) {
                    button.text('Не нравится (' + data.dislikes + ')');
                }
            });
        });
    });
    </script>
{% endblock %}